# Generated by Django 5.2.2 on 2025-06-10 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.programterm')),
            ],
            options={
                'unique_together': {('term', 'teacher', 'subject')},
            },
        ),
    ]
