from django.urls import path
from .views import (
    SignupView, DashboardView, SchoolListView, SchoolCreateView, SchoolUpdateView, SchoolDeleteView,
    ClassYearListView, ClassYearCreateView, ClassYearUpdateView, ClassYearDeleteView,
    SubjectListView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView,
    DirectorListView, DirectorCreateView, DirectorUpdateView, DirectorDeleteView,
    TeacherListView, TeacherCreateView, TeacherUpdateView, TeacherDeleteView,
    ProgramTermListView, ProgramTermCreateView, ProgramTermUpdateView, ProgramTermDeleteView,
    StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView,
    ParentListView, ParentCreateView, ParentUpdateView, ParentDeleteView,
    GradeListView, GradeCreateView, GradeUpdateView, GradeDeleteView,
    AttendanceListView, AttendanceCreateView, AttendanceUpdateView, AttendanceDeleteView,
    ParentAddChildView
)

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('schools/', SchoolListView.as_view(), name='school_list'),
    path('schools/add/', SchoolCreateView.as_view(), name='school_add'),
    path('schools/<int:pk>/edit/', SchoolUpdateView.as_view(), name='school_edit'),
    path('schools/<int:pk>/delete/', SchoolDeleteView.as_view(), name='school_delete'),
    path('classyears/', ClassYearListView.as_view(), name='classyear_list'),
    path('classyears/add/', ClassYearCreateView.as_view(), name='classyear_add'),
    path('classyears/<int:pk>/edit/', ClassYearUpdateView.as_view(), name='classyear_edit'),
    path('classyears/<int:pk>/delete/', ClassYearDeleteView.as_view(), name='classyear_delete'),
    path('subjects/', SubjectListView.as_view(), name='subject_list'),
    path('subjects/add/', SubjectCreateView.as_view(), name='subject_add'),
    path('subjects/<int:pk>/edit/', SubjectUpdateView.as_view(), name='subject_edit'),
    path('subjects/<int:pk>/delete/', SubjectDeleteView.as_view(), name='subject_delete'),
    path('directors/', DirectorListView.as_view(), name='director_list'),
    path('directors/add/', DirectorCreateView.as_view(), name='director_add'),
    path('directors/<int:pk>/edit/', DirectorUpdateView.as_view(), name='director_edit'),
    path('directors/<int:pk>/delete/', DirectorDeleteView.as_view(), name='director_delete'),
    path('teachers/', TeacherListView.as_view(), name='teacher_list'),
    path('teachers/add/', TeacherCreateView.as_view(), name='teacher_add'),
    path('teachers/<int:pk>/edit/', TeacherUpdateView.as_view(), name='teacher_edit'),
    path('teachers/<int:pk>/delete/', TeacherDeleteView.as_view(), name='teacher_delete'),
    path('terms/', ProgramTermListView.as_view(), name='term_list'),
    path('terms/add/', ProgramTermCreateView.as_view(), name='term_add'),
    path('terms/<int:pk>/edit/', ProgramTermUpdateView.as_view(), name='term_edit'),
    path('terms/<int:pk>/delete/', ProgramTermDeleteView.as_view(), name='term_delete'),
    path('students/', StudentListView.as_view(), name='student_list'),
    path('students/add/', StudentCreateView.as_view(), name='student_add'),
    path('students/<int:pk>/edit/', StudentUpdateView.as_view(), name='student_edit'),
    path('students/<int:pk>/delete/', StudentDeleteView.as_view(), name='student_delete'),
    path('parents/', ParentListView.as_view(), name='parent_list'),
    path('parents/add/', ParentCreateView.as_view(), name='parent_add'),
    path('parents/<int:pk>/edit/', ParentUpdateView.as_view(), name='parent_edit'),
    path('parents/<int:pk>/delete/', ParentDeleteView.as_view(), name='parent_delete'),
    path('grades/', GradeListView.as_view(), name='grade_list'),
    path('grades/add/', GradeCreateView.as_view(), name='grade_add'),
    path('grades/<int:pk>/edit/', GradeUpdateView.as_view(), name='grade_edit'),
    path('grades/<int:pk>/delete/', GradeDeleteView.as_view(), name='grade_delete'),
    path('attendance/', AttendanceListView.as_view(), name='attendance_list'),
    path('attendance/add/', AttendanceCreateView.as_view(), name='attendance_add'),
    path('attendance/<int:pk>/edit/', AttendanceUpdateView.as_view(), name='attendance_edit'),
    path('attendance/<int:pk>/delete/', AttendanceDeleteView.as_view(), name='attendance_delete'),
    path('parents/add-child/', ParentAddChildView.as_view(), name='parent_add_child'),
]
